# Generated by Django 4.2.4 on 2023-08-23 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_note_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='statelist',
        ),
    ]
