# Generated by Django 4.2.4 on 2023-08-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_note_app', '0002_delete_statelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'state',
                'managed': True,
            },
        ),
    ]
